# Welcome to Jekyll!

# Website settings
title: Jorge Enrique
description: Jorges's blog,use Jekyll and github pages.
keywords: Jorge,blog,Jekyll,github,gh-pages
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage'
url:  # url should be changed to 'http://www.jack003.com/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be changed to '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Jorge Enrique # Be used at blog posts' author.
  first_name: Jorge  # Be used at index page about me section.
  last_name: De La Cruz  # Be used at index page about me section.
  cv: #http://cv.jack003  # A online CV can be printed as PDF, leave blank if you don't have now
  email: jorge.cruz.arcia@rwth-aachen.de  # Leave blank if you don't have now
  facebook_username: jdelacruz26  # Leave blank if you don't have now
  github_username: jdelacruz26  # Leave blank if you don't have now
  avatar: /static/assets/img/landing/profile.png  # upload your avatar at directory and edit it.
  skill_icon1:
    - name: icon-python
    - name: icon-c
  skill_icon2:
    - name: icon-angular
    - name: icon-docker
  desc: Soy Ingeniero Mecánico, pero interesado por todas las disciplinas de la Ingeniería y de otras ramas del conociento. Creo que nunca debemos reusarnos a continuar aprendiendo ya sea en tu área de especialización o cualquier otra. ¡Por lo cual trato de aprender algo nuevo cada día!

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: https-jdelacruz26-github-io
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-91138706-1

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id: a49d4901c7853da9

## donation
donation: on  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
